config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root to: 'home#index'
  get 'pages/index'
  devise_for :users 
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      #root 'devise/sessions#new', as: :unauthenticated_root
      root 'home#index', as: :unauthenticated_root
    end
  end
  namespace :admin do
    get '/', to: 'home#index'
    resources :services
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :user
  has_one :pre_order
  has_one :order
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :equipment
  belongs_to :pre_order
  has_many :services, through: :order_details
  has_one :order, through: :equipment
  has_many :warranties
  has_many :stages
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :service
  belongs_to :order
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/pre_order.rb
class PreOrder < ApplicationRecord
  belongs_to :equipment
  has_many :pre_order_details
  has_many :services, through: :pre_order_details
  has_many :orders, through: :equipment
end

app/models/pre_order_detail.rb
class PreOrderDetail < ApplicationRecord
  belongs_to :pre_order
  belongs_to :service
end

app/models/service.rb
class Service < ApplicationRecord
    has_many :pre_order_details
    has_many :pre_orders, through: :pre_order_details
    has_one :order_detail
    has_many :orders, through: :order_details

    validates :name, presence: true
    validates :amount, presence: true
end

app/models/stage.rb
class Stage < ApplicationRecord
    belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  enum role: [:enduser, :operator, :admin]
  after_initialize :set_default_role, :if => :new_record?

  has_many :equipment
  

  

  def set_default_role
    self.role ||= :enduser
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/warranty.rb
class Warranty < ApplicationRecord
  belongs_to :order
end

app/controllers/admin/services_controller.rb
module Admin
  class ServicesController < AdminController
    before_action :set_service, only: [:id, :show, :edit, :update, :destroy]

    def index
      @services = Service.all.order(id: :asc)
    end
  
    def new
      @service = Service.new
    end

    def create
      @service = Service.new(service_params)
      respond_to do |format|
        if @service.save
          format.js
        else
          format.js
        end
      end
    end

    def show
    end

    def edit
    end

    def update
      respond_to do |format|
        if @service.update(service_params)
          format.js
        else
          format.js
        end
      end
    end

    def destroy
      @service.destroy
      respond_to do |format|
        format.js
      end
    end

    private

    def service_params
      params.require(:service).permit(:name, :amount)
    end

    def set_service
      @service = Service.find(params[:id])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit
    protect_from_forgery with: :exception
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    def after_sign_in_path_for(resource)
        if resource.admin? || resource.operator?
            admin_path
        else
            authenticated_root_path
        end
    end

    private

    def user_not_authorized
        puts current_user.id, @current_user.admin?
        flash[:notice] = "Sorry, You Are Not Authorized To Do This"
        redirect_to(request.referrer || root_path)
    end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    authorize Post
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    unless signed_in?
      redirect_to new_user_session_path
    else
      authorize Post
      @post = Post.new(post_params)
      respond_to do |format|
        if @post.save
          format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
  end
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/services_helper.rb
module Admin::ServicesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/admin/services/_errors.html.erb
<ul>
    <% service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
</ul>

app/views/admin/services/_form.html.erb
<%= form_with(model: [:admin, service], local: false) do |form|%>
    <div class="modal-body">
        <div id="errors-area">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Nombre del Servicio</label>
            <%= form.text_field :name, class:"form-control"%>
        </div>
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Monto</label>
            <%= form.text_field :amount, class:"form-control"%>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="btn-close-new">Close</button>
        <%= form.submit "save" , class: "btn btn-primary"%>
    </div>
<% end %>

app/views/admin/services/_service_row.html.erb
<tr id="service_row_<%= service.id %>">
    <td><%= service.id %></td>
    <td><%= service.name%></td>
    <td><%= service.amount%></td>
    <td>
        <%= link_to "Edit", edit_admin_service_path(service), data: {bs_toggle: "modal", bs_target: "#editModal", remote: true}, class: "btn btn-success" %> 
        <%= link_to "Delete", admin_service_path(service), method: :delete, data: {confirm: "Estas Seguro de Eliminarlo?", remote: true}, class: "btn btn-danger" %>
    </td>
</tr>

app/views/admin/services/_show.html.erb
<div class="modal-body">
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="btn-close-show">Close</button>
</div>

app/views/admin/services/create.js.erb
<% if @service.errors.any? %>
    $("#errors-area").html("<%= escape_javascript render('errors', service: @service) %>")
<% else %>
    $('#servicesTable').append("<%= escape_javascript render('service_row', service: @service) %>")
    $('#btn-close-new').click()
<% end %>

app/views/admin/services/destroy.js.erb
$("#service_row_<%= @service.id %>").remove()

app/views/admin/services/edit.js.erb
$('#editUserForm').html("<%= escape_javascript render('form', service: @service) %>")
$('#btn-close-new').click()

app/views/admin/services/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
        <th colspan="4" style="text-align: right;">
            <%= link_to "Agg Servicio", new_admin_service_path, data: {bs_toggle: "modal", bs_target: "#newModal", remote: true}, class: "btn btn-primary"%>
        </th>
    </tr>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Amount</th>
    </tr>
  </thead>
  <tbody id="servicesTable">
    <% @services.each do |service|%>
        <%= render 'service_row', service: service %>
    <% end %>
  </tbody>
</table>

<!-- Modal New -->
<div class="modal fade" id="newModal" tabindex="-1" aria-labelledby="newModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newModalLabel">Agg Servicio</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id="newUserForm">
        
      </div>
    </div>
  </div>
</div>

<!-- Modal Edit -->
<div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="editModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editModalLabel">Edit Servicio</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id="editUserForm">
        
      </div>
    </div>
  </div>
</div>

app/views/admin/services/new.js.erb
$('#newUserForm').html("<%= escape_javascript render('form', service: @service) %>")

app/views/admin/services/update.js.erb
<% if @service.errors.any? %>
    $("#errors-area").html("<%= escape_javascript render('errors', service: @service) %>")
<% else %>
    $("#service_row_<%= @service.id %>").replaceWith("<%= escape_javascript render('service_row', service: @service) %>")
    $("#btn-close-new").click()
<% end %>